name: diff_search
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.12
  - numpy
  - torch
  - transformers
  - tqdm
  - faiss-cpu
  - jina
  - sentence-transformers
  - fire
  - pip
  - pip:
      - tiktoken
